layer_id: "MODIS_Aqua_CorrectedReflectance_TrueColor_v6_STD"
layer_title: "Corrected Reflectance (True Color, v6, Standard, MODIS, Aqua)"
layer_name: "MODIS_Aqua_CorrectedReflectance_TrueColor tileset"
projection: "EPSG:3031"
tilematrixset: "250m"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_CorrectedReflectance_TrueColor abstract"
metadata:
  - {}
source_mrf:
  size_x: 32768
  size_y: 32768
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg3031"
  data_file_uri: "{S3_URL}/epsg3031"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"