layer_id: "Raster_Status"
layer_title: "Raster_Status (Blue Marble MODIS)"
layer_name: "Raster_Status tileset"
projection: "EPSG:4326"
tilematrixset: "16km"
mime_type: "image/jpeg"
static: false
abstract: "Raster_Status abstract"
time_config: "DETECT"
cache_expiration: 1200
metadata:
  - {}
source_mrf:
  size_x: 2560
  size_y: 1280
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/oe-status"
  data_file_path: "/onearth/layers/oe-status"
  year_dir: false
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"