layer_id: "MODIS_Aqua_CorrectedReflectance_Bands721_v6_STD"
layer_title: "Corrected Reflectance (Bands 7-2-1, MODIS, Aqua)"
layer_name: "MODIS_Aqua_CorrectedReflectance_Bands721 tileset"
projection: "EPSG:3413"
tilematrixset: "250m"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_CorrectedReflectance_Bands721 abstract"
metadata:
  - {}
source_mrf:
  size_x: 32768
  size_y: 32768
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg3413"
  data_file_uri: "{S3_URL}/epsg3413"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"