time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg3413", "nrt"]
gc_service_uri: "http://onearth-capabilities/wmts/epsg3413/nrt/gc"
exclude_layers:
  - 'Reference_Labels'
  - 'Reference_Labels_15m'
  - 'Reference_Features'
  - 'Reference_Features_15m'
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg3413/nrt/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/wmts/epsg3413/nrt/"
base_uri_gts: "http://localhost/twms/epsg3413/nrt/"
base_uri_meta: "https://gibs.earthdata.nasa.gov"
epsg_code: "EPSG:3413"
gc_service:
  internal_endpoint: "/var/www/html/wmts/epsg3413/nrt"
  external_endpoint: "/wmts/epsg3413/nrt/gc"
  config_prefix: "epsg3413_nrt_gc_service"
  gc_header_file: "/etc/onearth/config/conf/epsg3413_nrt_header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/epsg3413_nrt_header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/epsg3413_nrt_header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/wmts/epsg3413/nrt"
  external_endpoint: "/wmts/epsg3413/nrt"
  config_prefix: "epsg3413_nrt"
twms_service:
  internal_endpoint: "/var/www/html/twms/epsg3413/nrt"
  external_endpoint: "/twms/epsg3413/nrt"
mapserver:
  redirect_endpoint: "/var/www/html/mapserver/epsg3413/nrt"
  external_endpoint: "/wms/epsg3413/nrt"
  internal_endpoint: "/var/www/html/wms/epsg3413/nrt"
  config_prefix: "epsg3413_nrt_wms_time_service"
  mapfile_header:  "/etc/onearth/config/mapserver/epsg3413.header"
  mapfile_location: "/etc/onearth/config/mapserver/epsg3413_nrt.map"
  source_wmts_gc_uri: "https://gibs.earthdata.nasa.gov/wmts/epsg3413/nrt/1.0.0/WMTSCapabilities.xml"