time_service_uri: "http://onearth-time-service/time_service/time"
time_service_keys: ["epsg3031", "std"]
gc_service_uri: "http://onearth-capabilities/wmts/epsg3031/std/gc"
exclude_layers:
  - 'Reference_Labels'
  - 'Reference_Labels_15m'
  - 'Reference_Features'
  - 'Reference_Features_15m'
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/epsg3031/std/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://localhost/wmts/epsg3031/std/"
base_uri_gts: "http://localhost/twms/epsg3031/std/"
base_uri_meta: "https://gibs.earthdata.nasa.gov"
epsg_code: "EPSG:3031"
gc_service:
  internal_endpoint: "/var/www/html/wmts/epsg3031/std"
  external_endpoint: "/wmts/epsg3031/std/gc"
  config_prefix: "epsg3031_std_gc_service"
  gc_header_file: "/etc/onearth/config/conf/epsg3031_std_header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/epsg3031_std_header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/epsg3031_std_header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/wmts/epsg3031/std"
  external_endpoint: "/wmts/epsg3031/std"
  config_prefix: "epsg3031_std"
twms_service:
  internal_endpoint: "/var/www/html/twms/epsg3031/std"
  external_endpoint: "/twms/epsg3031/std"
mapserver:
  redirect_endpoint: "/var/www/html/mapserver/epsg3031/std"
  external_endpoint: "/wms/epsg3031/std"
  internal_endpoint: "/var/www/html/wms/epsg3031/std"
  config_prefix: "epsg3031_std_wms_time_service"
  mapfile_header:  "/etc/onearth/config/mapserver/epsg3031.header"
  mapfile_location: "/etc/onearth/config/mapserver/epsg3031_std.map"
  source_wmts_gc_uri: "https://gibs.earthdata.nasa.gov/wmts/epsg3031/std/1.0.0/WMTSCapabilities.xml"