source_gc_uri: "http://onearth-tile-services/oe-status/wmts.cgi?SERVICE=WMTS&REQUEST=GetCapabilities&VERSION=1.0.0"
time_service_uri: "http://onearth-time-service/time_service/time"
gc_service_uri: "http://onearth-capabilities/oe-status_reproject/gc"
tms_defs_file: "/etc/onearth/config/conf/tilematrixsets.xml"
layer_config_source: "/etc/onearth/config/layers/oe-status/"
apache_config_location: "/etc/httpd/conf.d/"
base_uri_gc: "http://onearth-tile-services/oe-status_reproject"
base_uri_gts: "http://onearth-tile-services/oe-status_reproject"
epsg_code: "EPSG:4326"
target_epsg_code: "EPSG:3857"
gc_service:
  internal_endpoint: "/var/www/html/oe-status_reproject"
  external_endpoint: "/oe-status_reproject/gc"
  config_prefix: "oe-status_reproject_gc_service"
  gc_header_file: "/etc/onearth/config/conf/header_gc.xml"
  gts_header_file: "/etc/onearth/config/conf/header_gts.xml"
  twms_gc_header_file: "/etc/onearth/config/conf/header_twms_gc.xml"
wmts_service:
  internal_endpoint: "/var/www/html/oe-status_reproject"
  external_endpoint: "/oe-status_reproject"
  config_prefix: "oe-status_reproject"
twms_service:
  internal_endpoint: "/var/www/html/oe-status_reproject"
  external_endpoint: "/oe-status_reproject"