layer_id: "MODIS_Aqua_Data_No_Data_v6_STD"
layer_title: "Data/No Data Mask (Day, v6, Standard, MODIS, Aqua)"
layer_name: "MODIS_Aqua_Data_No_Data tileset"
projection: "EPSG:4326"
tilematrixset: "250m"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_Data_No_Data abstract"
metadata:
  - {}
source_mrf:
  size_x: 163840
  size_y: 81920
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326"
  data_file_uri: "{S3_URL}/epsg4326"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"