layer_id: "MODIS_Aqua_SurfaceReflectance_Bands121_v6_STD"
layer_title: "Land Surface Reflectance (Bands 1-2-1, v6, Standard, MODIS, Aqua)"
layer_name: "MODIS_Aqua_SurfaceReflectance_Bands121_v6_STD tileset"
projection: "EPSG:4326"
tilematrixset: "250m"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_SurfaceReflectance_Bands121_v6_STD abstract"
metadata:
  - {}
source_mrf:
  size_x: 163840
  size_y: 81920
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326"
  data_file_uri: "{S3_URL}/epsg4326"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"