layer_id: "MODIS_Aqua_SurfaceReflectance_Bands143_v6_STD"
layer_title: "Surface Reflectance (Bands 1-4-3, MODIS, Aqua)"
layer_name: "MODIS_Aqua_SurfaceReflectance_Bands143 tileset"
projection: "EPSG:4326"
tilematrixset: "500m"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_SurfaceReflectance_Bands143 abstract"
metadata:
  - {}
source_mrf:
  size_x: 81920
  size_y: 40960
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326"
  data_file_uri: "{S3_URL}/epsg4326"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/etc/onearth/empty_tiles/Blank_RGB_512.jpg"