layer_id: "ASTER_L1T_Radiance_Terrain_Corrected"
layer_title: "Registered Radiance at the Sensor (Precision Terrain Corrected, ASTER)"
layer_name: "ASTER L1T Radiance Terrain Corrected tileset"
projection: "EPSG:4326"
tilematrixset: "15.625m"
mime_type: "image/png"
static: false
abstract: "ASTER_L1T_Radiance_Terrain_Corrected abstract"
metadata:
  - {}
source_mrf:
  size_x: 2621440
  size_y: 1310720
  bands: 4
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326/ASTER_L1T_Radiance_Terrain_Corrected/"
  data_file_uri: "{S3_URL}/epsg4326/ASTER_L1T_Radiance_Terrain_Corrected/"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/onearth/empty_tiles/ASTER_L1T_Radiance_Terrain_Corrected.png"