layer_id: "MODIS_Aqua_CorrectedReflectance_Bands721"
layer_title: "Corrected Reflectance (Bands 7-2-1, MODIS, Aqua)"
layer_name: "MODIS_Aqua_CorrectedReflectance_Bands721 tileset"
projection: "EPSG:4326"
tilematrixset: "250m"
mime_type: "image/jpeg"
static: false
abstract: "MODIS_Aqua_CorrectedReflectance_Bands721 abstract"
metadata:
  - {}
source_mrf:
  size_x: 163840
  size_y: 81920
  bands: 3
  tile_size_x: 512
  tile_size_y: 512
  idx_path: "/onearth/idx/epsg4326/MODIS_Aqua_CorrectedReflectance_Bands721/"
  data_file_uri: "{S3_URL}/epsg4326/MODIS_Aqua_CorrectedReflectance_Bands721/"
  year_dir: true
  bbox: -180,-90,180,90
  empty_tile: "/onearth/empty_tiles/Blank_RGB_512.jpg"